
services:
  postgres-db:
    image: postgres:16-alpine
    container_name: scouting_postgres_db
    environment:
      POSTGRES_DB: ScoutingToolDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YourNewStrongPassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  scouting-api:
    build:
      context: ./ScoutingTool.Api
      dockerfile: Dockerfile
    container_name: scouting_web_api
    ports:
      - "5219:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=localhost;Port=5432;Database=ScoutingToolDB;Username=postgres;Password=YourNewStrongPassword
    depends_on:
      postgres-db:
        condition: service_healthy

volumes:
  postgres_data: